# Generated by Django 5.0.6 on 2024-09-22 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "course",
            "0003_course_last_activity_by_requirement_last_activity_by_and_more",
        ),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="course",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="course",
            name="duration_in_weeks",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="popularity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="course",
            name="requirements",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="course.requirement"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["slug", "popularity"], name="course_cour_slug_dc845d_idx"
            ),
        ),
    ]
