# Generated by Django 5.0.6 on 2024-12-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_rename_duration_in_weeks_course_duration_in_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="facilityclass",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
