# Generated by Django 5.0.6 on 2024-12-29 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0006_alter_course_slug_alter_facilityclass_slug_and_more"),
        ("enrollment", "0014_alter_attendeeclassenrollment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilityclass",
            name="facility_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_facility_enrollments",
                to="enrollment.facilityenrollment",
                verbose_name="Facility Enrollment",
            ),
        ),
    ]
